// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBgi5YlcZq09CCtuez-243oATOmZ_V3LiU",
      authDomain: "security-management-2e618.firebaseapp.com",
      projectId: "security-management-2e618",
      storageBucket: "security-management-2e618.appspot.com",
      messagingSenderId: "255786991407",
      appId: "1:255786991407:web:3d960ac961d6a6d9c02bda");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBgi5YlcZq09CCtuez-243oATOmZ_V3LiU",
      authDomain: "security-management-2e618.firebaseapp.com",
      projectId: "security-management-2e618",
      storageBucket: "security-management-2e618.appspot.com",
      messagingSenderId: "255786991407",
      appId: "1:255786991407:web:3d960ac961d6a6d9c02bda");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBgi5YlcZq09CCtuez-243oATOmZ_V3LiU",
      authDomain: "security-management-2e618.firebaseapp.com",
      projectId: "security-management-2e618",
      storageBucket: "security-management-2e618.appspot.com",
      messagingSenderId: "255786991407",
      appId: "1:255786991407:web:3d960ac961d6a6d9c02bda");

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyBgi5YlcZq09CCtuez-243oATOmZ_V3LiU",
      authDomain: "security-management-2e618.firebaseapp.com",
      projectId: "security-management-2e618",
      storageBucket: "security-management-2e618.appspot.com",
      messagingSenderId: "255786991407",
      appId: "1:255786991407:web:3d960ac961d6a6d9c02bda");
}
